CREATE TABLE `agmednet_02` (
  `idagmednet_02` int NOT NULL AUTO_INCREMENT,
  `trial` varchar(45) DEFAULT NULL,
  `transmittal_form_name` varchar(100) DEFAULT NULL,
  `study_instance_uid` varchar(255) DEFAULT NULL,
  `exam_transfer_date` datetime DEFAULT NULL,
  `exam_date` date DEFAULT NULL,
  `patient_id` varchar(45) DEFAULT NULL,
  `dicom_study_date` date DEFAULT NULL,
  `acquisition_start_time` time DEFAULT NULL,
  `non_dicom_study_date` date DEFAULT NULL,
  `acquisition_end_time` time DEFAULT NULL,
  `examination` varchar(255) DEFAULT NULL,
  `stress_tests_other` varchar(45) DEFAULT NULL,
  `lung_nodule_follow_up_other` varchar(100) DEFAULT NULL,
  `other_tests_other` varchar(255) DEFAULT NULL,
  `site_contact_submitter` varchar(100) DEFAULT NULL,
  `date_of_submission` date DEFAULT NULL,
  `dicomscandate` date DEFAULT NULL,
  `dicomimagedata` varchar(255) DEFAULT NULL,
  `dicomacqstart` double DEFAULT NULL,
  `hidecct` varchar(45) DEFAULT NULL,
  `hideica` varchar(45) DEFAULT NULL,
  `hidecacs` varchar(45) DEFAULT NULL,
  `hidenonmain` varchar(45) DEFAULT NULL,
  `hidedicom` varchar(45) DEFAULT NULL,
  `hidenotdicom` varchar(45) DEFAULT NULL,
  `additional_comments` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`idagmednet_02`)
) ENGINE=InnoDB AUTO_INCREMENT=2414 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci